---
- name: Update dns
  hosts: localhost
  gather_facts: false
  module_defaults:

    community.general.nsupdate:
      key_name: "{{ tsig_key_name }}"
      key_secret: "{{ tsig_key_secret }}"
      key_algorithm: "{{ tsig_key_algorithm }}"
      server: "{{ tsig_server }}"

  tasks:

    - name: Import update task
      ansible.builtin.import_tasks:
        file: tasks/dns/update.yml
